//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Client
    {
        public long Sys_Id { get; set; }
        public long Sys_IdCompany { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_BusinessName { get; set; }
        public string Sys_Tradename { get; set; }
        public string Sys_Email { get; set; }
        public string Sys_Street { get; set; }
        public string Sys_ZipCode { get; set; }
        public string Sys_Municipality { get; set; }
        public string Sys_State { get; set; }
        public string Sys_Cologne { get; set; }
        public string Sys_Country { get; set; }
        public System.DateTime Sys_RegistrationDate { get; set; }
        public System.DateTime Sys_ModificationDate { get; set; }
        public long Sys_UserId { get; set; }
        public string Sys_RfcCompany { get; set; }
    }
}
