//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public int Sys_Id { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_Usr { get; set; }
        public string Sys_Pass { get; set; }
        public string Sys_Email { get; set; }
        public Nullable<int> Sys_AccessAttempts { get; set; }
        public Nullable<System.DateTime> Sys_LockDate { get; set; }
        public System.DateTime Sys_CreationDate { get; set; }
        public Nullable<System.DateTime> Sys_LastLoggin { get; set; }
        public Nullable<int> Sys_Status { get; set; }
        public Nullable<int> Sys_Profile_Id { get; set; }
    }
}
