//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Certificate
    {
        public int Sys_Id { get; set; }
        public long Sys_IdCompany { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_Number { get; set; }
        public string Sys_Name { get; set; }
        public string Sys_Certificate1 { get; set; }
        public string Sys_Key { get; set; }
        public string Sys_Pwd { get; set; }
        public System.DateTime Sys_RegistrationDate { get; set; }
        public System.DateTime Sys_RegistrationDateCert { get; set; }
        public System.DateTime Sys_ExpirationDateCert { get; set; }
    }
}
