//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Company
    {
        public int Sys_Id { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_Name { get; set; }
        public string Sys_FiscalRegime { get; set; }
        public string Sys_Curp { get; set; }
        public string Sys_Page { get; set; }
        public string Sys_Email { get; set; }
        public string Sys_Phone { get; set; }
        public string Sys_UserModified { get; set; }
        public System.DateTime Sys_RegistrationDate { get; set; }
        public Nullable<System.DateTime> Sys_ModificationDate { get; set; }
        public Nullable<bool> Sys_Status { get; set; }
        public Nullable<int> Sys_Balance { get; set; }
    }
}
