//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu_Usuario
    {
        public int Sys_Id { get; set; }
        public int Sys_Menu_Id { get; set; }
        public int Sys_Usuario_Id { get; set; }
    }
}
