//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Cliente
    {
        public int Sys_Id { get; set; }
        public string Sys_RFC { get; set; }
        public string Sys_Razon_Social { get; set; }
        public string Sys_Nombre_Comercial { get; set; }
        public string Sys_Correo { get; set; }
        public string Sys_Calle { get; set; }
        public string Sys_CP { get; set; }
        public string Sys_Municipio { get; set; }
        public string Sys_Estado { get; set; }
        public string Sys_Colonia { get; set; }
        public string Sys_Pais { get; set; }
        public System.DateTime Sys_Fecha_Registro { get; set; }
        public System.DateTime Sys_Fecha_Modificacion { get; set; }
        public int Sys_Usuario_Id { get; set; }
        public string Sys_Empresa_Rfc { get; set; }
    }
}
