//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Empresa
    {
        public int Sys_Id { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_Nombre { get; set; }
        public string Sys_Regimen_Fiscal { get; set; }
        public string Sys_Curp { get; set; }
        public string Sys_Pagina { get; set; }
        public string Sys_Correo { get; set; }
        public string Sys_Telefono { get; set; }
        public string Sys_Usr_Modif { get; set; }
        public System.DateTime Sys_Fec_Registro { get; set; }
        public Nullable<System.DateTime> Sys_Fec_Modf { get; set; }
        public Nullable<bool> Sys_Activo { get; set; }
    }
}
