//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Tipo_Sistema
    {
        public int Sys_Id { get; set; }
        public string Sys_Nombre { get; set; }
    }
}
