//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Certificado
    {
        public int Sys_Id { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_Numero { get; set; }
        public string Sys_Nombre { get; set; }
        public string Sys_Certificado1 { get; set; }
        public string Sys_Key { get; set; }
        public string Sys_Pwd { get; set; }
        public System.DateTime Sys_Fec_Registro { get; set; }
        public System.DateTime Sys_Fec_Alta { get; set; }
        public System.DateTime Sys_Fec_Vencimiento { get; set; }
    }
}
