//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Dir_Empresa
    {
        public int Sys_Id { get; set; }
        public string Sys_Rfc { get; set; }
        public string Sys_CodPos { get; set; }
        public string Sys_Calle { get; set; }
        public string Sys_No_Exterior { get; set; }
        public string Sys_No_Interior { get; set; }
        public string Sys_Colonia { get; set; }
        public string Sys_Municipio { get; set; }
        public string Sys_Referencia { get; set; }
        public string Sys_Estado { get; set; }
        public string Sys_Pais { get; set; }
        public string Sys_Usr_Modif { get; set; }
        public System.DateTime Sys_Fec_Registro { get; set; }
        public Nullable<System.DateTime> Sys_Fec_Modf { get; set; }
    }
}
