//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioContract
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Certificado> Sys_Certificado { get; set; }
        public virtual DbSet<Sys_Dir_Empresa> Sys_Dir_Empresa { get; set; }
        public virtual DbSet<Sys_Empresa> Sys_Empresa { get; set; }
        public virtual DbSet<Sys_Menu> Sys_Menu { get; set; }
        public virtual DbSet<Sys_Perfiles> Sys_Perfiles { get; set; }
        public virtual DbSet<Sys_Tipo_Sistema> Sys_Tipo_Sistema { get; set; }
        public virtual DbSet<Sys_Usuario> Sys_Usuario { get; set; }
        public virtual DbSet<Sys_Menu_Usuario> Sys_Menu_Usuario { get; set; }
        public virtual DbSet<Sys_Cliente> Sys_Cliente { get; set; }
    }
}
