//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 




namespace Nomina12Cfdi
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/nomina12", IsNullable = false, ElementName = "Nomina")]
    public partial class Nomina12
    {

        [XmlAttribute(Namespace = System.Xml.Schema.XmlSchema.InstanceNamespace)] public string schemaLocation =
            "http://www.sat.gob.mx/nomina12 http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Complementoscfdi/nomina12.xsd";

        [XmlIgnore]
        public string SerFol { get; set; }

        [XmlIgnore]
        public string ForPag { get; set; }

        [XmlIgnore]
        public string MetPag { get; set; }

        private NominaEmisor emisorField;

        private NominaReceptor receptorField;

        private NominaPercepciones12 percepcionesField;

        private NominaDeducciones12 deduccionesField;

        private NominaOtroPago[] otrosPagosField;

        private NominaIncapacidad12[] incapacidadesField;

        private string versionField;

        private string tipoNominaField;

        private string fechaPagoField;

        private string fechaInicialPagoField;

        private string fechaFinalPagoField;

        private decimal numDiasPagadosField;

        private string totalPercepcionesField;

        private string totalDeduccionesField;

        private string totalOtrosPagosField;

        public Nomina12()
        {
            this.versionField = "1.2";
        }

        /// <remarks/>
        public NominaEmisor Emisor
        {
            get { return this.emisorField; }
            set { this.emisorField = value; }
        }

        /// <remarks/>
        public NominaReceptor Receptor
        {
            get { return this.receptorField; }
            set { this.receptorField = value; }
        }

        /// <remarks/>
        public NominaPercepciones12 Percepciones
        {
            get { return this.percepcionesField; }
            set { this.percepcionesField = value; }
        }

        /// <remarks/>
        public NominaDeducciones12 Deducciones
        {
            get { return this.deduccionesField; }
            set { this.deduccionesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OtroPago", IsNullable = false)]
        public NominaOtroPago[] OtrosPagos
        {
            get { return this.otrosPagosField; }
            set { this.otrosPagosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Incapacidad", IsNullable = false)]
        public NominaIncapacidad12[] Incapacidades
        {
            get { return this.incapacidadesField; }
            set { this.incapacidadesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoNomina
        {
            get { return this.tipoNominaField; }
            set { this.tipoNominaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaPago
        {
            get { return this.fechaPagoField; }
            set { this.fechaPagoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaInicialPago
        {
            get { return this.fechaInicialPagoField; }
            set { this.fechaInicialPagoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaFinalPago
        {
            get { return this.fechaFinalPagoField; }
            set { this.fechaFinalPagoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NumDiasPagados
        {
            get { return this.numDiasPagadosField; }
            set { this.numDiasPagadosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalPercepciones
        {
            get { return this.totalPercepcionesField; }
            set { this.totalPercepcionesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalDeducciones
        {
            get { return this.totalDeduccionesField; }
            set { this.totalDeduccionesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalOtrosPagos
        {
            get { return this.totalOtrosPagosField; }
            set { this.totalOtrosPagosField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaEmisor
    {

        private NominaEmisorEntidadSNCF entidadSNCFField;

        private string curpField;

        private string registroPatronalField;

        private string rfcPatronOrigenField;

        /// <remarks/>
        public NominaEmisorEntidadSNCF EntidadSNCF
        {
            get { return this.entidadSNCFField; }
            set { this.entidadSNCFField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curp
        {
            get { return this.curpField; }
            set { this.curpField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegistroPatronal
        {
            get { return this.registroPatronalField; }
            set { this.registroPatronalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcPatronOrigen
        {
            get { return this.rfcPatronOrigenField; }
            set { this.rfcPatronOrigenField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaEmisorEntidadSNCF
    {

        private string origenRecursoField;

        private string montoRecursoPropioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrigenRecurso
        {
            get { return this.origenRecursoField; }
            set { this.origenRecursoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MontoRecursoPropio
        {
            get { return this.montoRecursoPropioField; }
            set { this.montoRecursoPropioField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaReceptor
    {

        //Campos agregados sin poner en la serialización
        [XmlIgnore]
        public string Nombre { get; set; }

        [XmlIgnore]
        public string ApellidoPaterno { get; set; }

        [XmlIgnore]
        public string ApellidoMaterno { get; set; }

        [XmlIgnore]
        public string FechaNacimiento { get; set; }

        [XmlIgnore]
        public string CorreoElectronico { get; set; }

        [XmlIgnore]
        public string Telefono { get; set; }

        [XmlIgnore]
        public string Calle { get; set; }

        [XmlIgnore]
        public string NumExterior { get; set; }

        [XmlIgnore]
        public string NumInterior { get; set; }

        [XmlIgnore]
        public string Colonia { get; set; }

        [XmlIgnore]
        public string CodPos { get; set; }

        [XmlIgnore]
        public string Pais { get; set; }

        [XmlIgnore]
        public string Ciudad { get; set; }

        [XmlIgnore]
        public string EstadoNacimiento { get; set; }

        [XmlIgnore]
        public string UsuarioNom { get; set; }

        [XmlIgnore]
        public string PwdNom { get; set; }

        [XmlIgnore]
        public string Estatus { get; set; }

        [XmlIgnore]
        public string Rfc { get; set; }

        [XmlIgnore]
        public string TipoTrabajador { get; set; }

        [XmlIgnore]
        public string IdSubContrato { get; set; }

        private NominaReceptorSubContratacion[] subContratacionField;

        private string curpField;

        private string numSeguridadSocialField;

        private string fechaInicioRelLaboralField;

        private string antigüedadField;

        private string tipoContratoField;

        private string sindicalizadoField;

        private bool sindicalizadoFieldSpecified;

        private string tipoJornadaField;

        private string tipoRegimenField;

        private string numEmpleadoField;

        private string departamentoField;

        private string puestoField;

        private string riesgoPuestoField;

        private string periodicidadPagoField;

        private string bancoField;

        private string cuentaBancariaField;

        private string salarioBaseCotAporField;

        private string salarioDiarioIntegradoField;

        private string claveEntFedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubContratacion")]
        public NominaReceptorSubContratacion[] SubContratacion
        {
            get { return this.subContratacionField; }
            set { this.subContratacionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curp
        {
            get { return this.curpField; }
            set { this.curpField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumSeguridadSocial
        {
            get { return this.numSeguridadSocialField; }
            set { this.numSeguridadSocialField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaInicioRelLaboral
        {
            get { return this.fechaInicioRelLaboralField; }
            set { this.fechaInicioRelLaboralField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Antigüedad
        {
            get { return this.antigüedadField; }
            set { this.antigüedadField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoContrato
        {
            get { return this.tipoContratoField; }
            set { this.tipoContratoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sindicalizado
        {
            get { return this.sindicalizadoField; }
            set { this.sindicalizadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SindicalizadoSpecified
        {
            get { return this.sindicalizadoFieldSpecified; }
            set { this.sindicalizadoFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoJornada
        {
            get { return this.tipoJornadaField; }
            set { this.tipoJornadaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoRegimen
        {
            get { return this.tipoRegimenField; }
            set { this.tipoRegimenField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumEmpleado
        {
            get { return this.numEmpleadoField; }
            set { this.numEmpleadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Departamento
        {
            get { return this.departamentoField; }
            set { this.departamentoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Puesto
        {
            get { return this.puestoField; }
            set { this.puestoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RiesgoPuesto
        {
            get { return this.riesgoPuestoField; }
            set { this.riesgoPuestoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PeriodicidadPago
        {
            get { return this.periodicidadPagoField; }
            set { this.periodicidadPagoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Banco
        {
            get { return this.bancoField; }
            set { this.bancoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CuentaBancaria
        {
            get { return this.cuentaBancariaField; }
            set { this.cuentaBancariaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SalarioBaseCotApor
        {
            get { return this.salarioBaseCotAporField; }
            set { this.salarioBaseCotAporField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SalarioDiarioIntegrado
        {
            get { return this.salarioDiarioIntegradoField; }
            set { this.salarioDiarioIntegradoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClaveEntFed
        {
            get { return this.claveEntFedField; }
            set { this.claveEntFedField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaReceptorSubContratacion
    {

        private string rfcLaboraField;

        private decimal porcentajeTiempoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcLabora
        {
            get { return this.rfcLaboraField; }
            set { this.rfcLaboraField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PorcentajeTiempo
        {
            get { return this.porcentajeTiempoField; }
            set { this.porcentajeTiempoField = value; }
        }

        [XmlIgnore]
        public long IdSubcontrato { get; set; }

        [XmlIgnore]
        public long IdEmpleado { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public enum NominaReceptorSindicalizado
    {

        /// <remarks/>
        Sí,

        /// <remarks/>
        No,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepciones12
    {

        private NominaPercepcionesPercepcion12[] percepcionField;

        private NominaPercepcionesJubilacionPensionRetiro jubilacionPensionRetiroField;

        private NominaPercepcionesSeparacionIndemnizacion separacionIndemnizacionField;

        private string totalSueldosField;

        private string totalSeparacionIndemnizacionField;

        private string totalJubilacionPensionRetiroField;

        private string totalGravadoField;

        private string totalExentoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Percepcion")]
        public NominaPercepcionesPercepcion12[] Percepcion
        {
            get { return this.percepcionField; }
            set { this.percepcionField = value; }
        }

        /// <remarks/>
        public NominaPercepcionesJubilacionPensionRetiro JubilacionPensionRetiro
        {
            get { return this.jubilacionPensionRetiroField; }
            set { this.jubilacionPensionRetiroField = value; }
        }

        /// <remarks/>
        public NominaPercepcionesSeparacionIndemnizacion SeparacionIndemnizacion
        {
            get { return this.separacionIndemnizacionField; }
            set { this.separacionIndemnizacionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalSueldos
        {
            get { return this.totalSueldosField; }
            set { this.totalSueldosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalSeparacionIndemnizacion
        {
            get { return this.totalSeparacionIndemnizacionField; }
            set { this.totalSeparacionIndemnizacionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalJubilacionPensionRetiro
        {
            get { return this.totalJubilacionPensionRetiroField; }
            set { this.totalJubilacionPensionRetiroField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalGravado
        {
            get { return this.totalGravadoField; }
            set { this.totalGravadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalExento
        {
            get { return this.totalExentoField; }
            set { this.totalExentoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcion12
    {

        private NominaPercepcionesPercepcionAccionesOTitulos accionesOTitulosField;

        private NominaPercepcionesPercepcionHorasExtra[] horasExtraField;

        private string tipoPercepcionField;

        private string claveField;

        private string conceptoField;

        private string importeGravadoField;

        private string importeExentoField;

        /// <remarks/>
        public NominaPercepcionesPercepcionAccionesOTitulos AccionesOTitulos
        {
            get { return this.accionesOTitulosField; }
            set { this.accionesOTitulosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HorasExtra")]
        public NominaPercepcionesPercepcionHorasExtra[] HorasExtra
        {
            get { return this.horasExtraField; }
            set { this.horasExtraField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoPercepcion
        {
            get { return this.tipoPercepcionField; }
            set { this.tipoPercepcionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave
        {
            get { return this.claveField; }
            set { this.claveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto
        {
            get { return this.conceptoField; }
            set { this.conceptoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImporteGravado
        {
            get { return this.importeGravadoField; }
            set { this.importeGravadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImporteExento
        {
            get { return this.importeExentoField; }
            set { this.importeExentoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcionAccionesOTitulos
    {

        private decimal valorMercadoField;

        private decimal precioAlOtorgarseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ValorMercado
        {
            get { return this.valorMercadoField; }
            set { this.valorMercadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PrecioAlOtorgarse
        {
            get { return this.precioAlOtorgarseField; }
            set { this.precioAlOtorgarseField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcionHorasExtra
    {

        private int diasField;

        private string tipoHorasField;

        private int horasExtraField;

        private string importePagadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Dias
        {
            get { return this.diasField; }
            set { this.diasField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoHoras
        {
            get { return this.tipoHorasField; }
            set { this.tipoHorasField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int HorasExtra
        {
            get { return this.horasExtraField; }
            set { this.horasExtraField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImportePagado
        {
            get { return this.importePagadoField; }
            set { this.importePagadoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesJubilacionPensionRetiro
    {

        private string totalUnaExhibicionField;

        private string totalParcialidadField;

        private string montoDiarioField;

        private string ingresoAcumulableField;

        private string ingresoNoAcumulableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalUnaExhibicion
        {
            get { return this.totalUnaExhibicionField; }
            set { this.totalUnaExhibicionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalParcialidad
        {
            get { return this.totalParcialidadField; }
            set { this.totalParcialidadField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MontoDiario
        {
            get { return this.montoDiarioField; }
            set { this.montoDiarioField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IngresoAcumulable
        {
            get { return this.ingresoAcumulableField; }
            set { this.ingresoAcumulableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IngresoNoAcumulable
        {
            get { return this.ingresoNoAcumulableField; }
            set { this.ingresoNoAcumulableField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesSeparacionIndemnizacion
    {

        private string totalPagadoField;

        private int numAñosServicioField;

        private string ultimoSueldoMensOrdField;

        private string ingresoAcumulableField;

        private string ingresoNoAcumulableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalPagado
        {
            get { return this.totalPagadoField; }
            set { this.totalPagadoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumAñosServicio
        {
            get { return this.numAñosServicioField; }
            set { this.numAñosServicioField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UltimoSueldoMensOrd
        {
            get { return this.ultimoSueldoMensOrdField; }
            set { this.ultimoSueldoMensOrdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IngresoAcumulable
        {
            get { return this.ingresoAcumulableField; }
            set { this.ingresoAcumulableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IngresoNoAcumulable
        {
            get { return this.ingresoNoAcumulableField; }
            set { this.ingresoNoAcumulableField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaDeducciones12
    {

        private NominaDeduccionesDeduccion12[] deduccionField;

        private string totalOtrasDeduccionesField;

        private string totalImpuestosRetenidosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Deduccion")]
        public NominaDeduccionesDeduccion12[] Deduccion
        {
            get { return this.deduccionField; }
            set { this.deduccionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalOtrasDeducciones
        {
            get { return this.totalOtrasDeduccionesField; }
            set { this.totalOtrasDeduccionesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalImpuestosRetenidos
        {
            get { return this.totalImpuestosRetenidosField; }
            set { this.totalImpuestosRetenidosField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaDeduccionesDeduccion12
    {

        private string tipoDeduccionField;

        private string claveField;

        private string conceptoField;

        private string importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoDeduccion
        {
            get { return this.tipoDeduccionField; }
            set { this.tipoDeduccionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave
        {
            get { return this.claveField; }
            set { this.claveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto
        {
            get { return this.conceptoField; }
            set { this.conceptoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Importe
        {
            get { return this.importeField; }
            set { this.importeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPago
    {

        private NominaOtroPagoSubsidioAlEmpleo subsidioAlEmpleoField;

        private NominaOtroPagoCompensacionSaldosAFavor compensacionSaldosAFavorField;

        private string tipoOtroPagoField;

        private string claveField;

        private string conceptoField;

        private string importeField;

        /// <remarks/>
        public NominaOtroPagoSubsidioAlEmpleo SubsidioAlEmpleo
        {
            get { return this.subsidioAlEmpleoField; }
            set { this.subsidioAlEmpleoField = value; }
        }

        /// <remarks/>
        public NominaOtroPagoCompensacionSaldosAFavor CompensacionSaldosAFavor
        {
            get { return this.compensacionSaldosAFavorField; }
            set { this.compensacionSaldosAFavorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoOtroPago
        {
            get { return this.tipoOtroPagoField; }
            set { this.tipoOtroPagoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave
        {
            get { return this.claveField; }
            set { this.claveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto
        {
            get { return this.conceptoField; }
            set { this.conceptoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Importe
        {
            get { return this.importeField; }
            set { this.importeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPagoSubsidioAlEmpleo
    {

        private string subsidioCausadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubsidioCausado
        {
            get { return this.subsidioCausadoField; }
            set { this.subsidioCausadoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPagoCompensacionSaldosAFavor
    {

        private string saldoAFavorField;

        private int añoField;

        private string remanenteSalFavField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SaldoAFavor
        {
            get { return this.saldoAFavorField; }
            set { this.saldoAFavorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Año
        {
            get { return this.añoField; }
            set { this.añoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RemanenteSalFav
        {
            get { return this.remanenteSalFavField; }
            set { this.remanenteSalFavField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina12")]
    public partial class NominaIncapacidad12
    {

        private int diasIncapacidadField;

        private string tipoIncapacidadField;

        private string importeMonetarioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DiasIncapacidad
        {
            get { return this.diasIncapacidadField; }
            set { this.diasIncapacidadField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoIncapacidad
        {
            get { return this.tipoIncapacidadField; }
            set { this.tipoIncapacidadField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImporteMonetario
        {
            get { return this.importeMonetarioField; }
            set { this.importeMonetarioField = value; }
        }
    }
}